"""Add duration_minutes to Exam and make Task.exam_id required

Revision ID: d504c08365f1
Revises: 002_add_exams_and_artifacts
Create Date: 2026-03-14 17:56:16.925278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd504c08365f1'
down_revision = '002_add_exams_and_artifacts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DIJ', 'QUESTION_PREVIEW', 'NES', 'VARIANTS_PACKAGE', 'ANSWER_MATRIX', name='artifacttype', native_enum=False),
               existing_nullable=False)
    
    # Add duration_minutes to exams table with proper migration strategy
    # Step 1: Add column as nullable
    op.add_column('exams', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # Step 2: Set default value for existing records
    op.execute('UPDATE exams SET duration_minutes = 60 WHERE duration_minutes IS NULL')
    # Step 3: Make column non-nullable
    op.alter_column('exams', 'duration_minutes', nullable=False)
    # Step 4: Add CHECK constraint
    op.create_check_constraint('check_duration_minutes_positive', 'exams', 'duration_minutes > 0')
    
    op.alter_column('exams', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', name='examstatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_exams_exam_id'), 'exams', ['exam_id'], unique=False)
    op.alter_column('task_logs', 'task_id',
               existing_type=sa.UUID(),
               comment='Parent task ID',
               existing_nullable=False)
    op.alter_column('task_logs', 'stage',
               existing_type=sa.VARCHAR(length=50),
               comment='Pipeline stage name',
               existing_nullable=True)
    op.alter_column('task_logs', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level', native_enum=False),
               comment='Log severity level',
               existing_nullable=False)
    op.alter_column('task_logs', 'message',
               existing_type=sa.TEXT(),
               comment='Human-readable log message',
               existing_nullable=False)
    op.alter_column('task_logs', 'data_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured metadata',
               existing_nullable=True)
    op.alter_column('task_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When log was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner of the task',
               existing_nullable=False)
    
    # Make tasks.exam_id non-nullable with proper migration strategy
    # Step 1: Delete tasks with NULL exam_id (as per data-model.md requirements)
    op.execute('DELETE FROM tasks WHERE exam_id IS NULL')
    # Step 2: Make column non-nullable
    op.alter_column('tasks', 'exam_id',
               existing_type=sa.UUID(),
               comment='Associated exam',
               nullable=False)
    
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='task_status', native_enum=False),
               comment='Current task status',
               existing_nullable=False)
    op.alter_column('tasks', 'current_stage',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EXTRACT_DOCX', 'AI_UNDERSTANDING', 'AI_ANALYSIS', 'SHUFFLE', 'RENDER_DOCX', name='task_stage', native_enum=False),
               comment='Current pipeline stage',
               existing_nullable=True)
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='Completion percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'retry_count_by_stage',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Map of stage name to retry count',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'error',
               existing_type=sa.TEXT(),
               comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               comment="Google's unique subject identifier",
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="User's email address",
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               comment="User's display name",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's display name",
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's email address",
               existing_nullable=False)
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Google's unique subject identifier",
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('tasks', 'retry_count_by_stage',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Map of stage name to retry count',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Completion percentage (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'current_stage',
               existing_type=sa.Enum('EXTRACT_DOCX', 'AI_UNDERSTANDING', 'AI_ANALYSIS', 'SHUFFLE', 'RENDER_DOCX', name='task_stage', native_enum=False),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Current pipeline stage',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='task_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Current task status',
               existing_nullable=False)
    op.alter_column('tasks', 'exam_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Associated exam',
               nullable=True)  # Revert to nullable (data cannot be restored)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner of the task',
               existing_nullable=False)
    op.alter_column('task_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When log was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_logs', 'data_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured metadata',
               existing_nullable=True)
    op.alter_column('task_logs', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable log message',
               existing_nullable=False)
    op.alter_column('task_logs', 'level',
               existing_type=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level', native_enum=False),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Log severity level',
               existing_nullable=False)
    op.alter_column('task_logs', 'stage',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Pipeline stage name',
               existing_nullable=True)
    op.alter_column('task_logs', 'task_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Parent task ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_exams_exam_id'), table_name='exams')
    op.alter_column('exams', 'status',
               existing_type=sa.Enum('DRAFT', 'PROCESSING', 'COMPLETED', name='examstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # Drop CHECK constraint and duration_minutes column
    op.drop_constraint('check_duration_minutes_positive', 'exams', type_='check')
    op.drop_column('exams', 'duration_minutes')
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.Enum('DIJ', 'QUESTION_PREVIEW', 'NES', 'VARIANTS_PACKAGE', 'ANSWER_MATRIX', name='artifacttype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
